### ISSUE TITLE
Can't receive packet larger than 16MB

### ISSUE THREAD

**Issue by bgrainger** [bgrainger/MySqlConnector#73]
Add the following to `InsertLargeBlob`:

```
[InlineData("LongBlob", 67108864)]
```

The test fails:

```
    SideBySide.DataTypes.InsertLargeBlob(column: "LongBlob", size: 16777216) [FAIL]
      System.FormatException : Not an EOF packet
      Stack Trace:
        MySqlConnector\src\MySqlConnector\Serialization\EofPayload.cs(17,0): at MySql.Data.Serialization.EofPayload.Create(PayloadData payload)
        MySqlConnector\src\MySqlConnector\MySqlClient\MySqlDataReader.cs(74,0): at MySql.Data.MySqlClient.MySqlDataReader.ReadAsyncRemainder(PayloadData payload)
        MySqlConnector\src\MySqlConnector\MySqlClient\MySqlDataReader.cs(67,0): at MySql.Data.MySqlClient.MySqlDataReader.<ReadAsyncAwaited>d__4.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        MySqlConnector\src\MySqlConnector\MySqlClient\MySqlDataReader.cs(41,0): at MySql.Data.MySqlClient.MySqlDataReader.Read()
           at Dapper.SqlMapper.<QueryImpl>d__124`1.MoveNext()
           at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
           at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
           at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
        MySqlConnector\tests\SideBySide.New\DataTypes.cs(492,0): at SideBySide.DataTypes.InsertLargeBlob(String column, Int32 size)
```

**Comment by bgrainger** [comment]
From https://dev.mysql.com/doc/internals/en/packet-EOF_Packet.html:

> Caution
> The EOF packet may appear in places where a Protocol::LengthEncodedInteger may appear. You must check whether the packet length is less than 9 to make sure that it is a EOF packet.

This can happen when reading a [`ProtocolText::ResultsetRow`](https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-ProtocolText::ResultsetRow) and the length is greater than 16MiB. The data will be sent as a [LengthEncodedString](https://dev.mysql.com/doc/internals/en/string.html#packet-Protocol::LengthEncodedString), which is prefixed with a [LengthEncodedInteger](https://dev.mysql.com/doc/internals/en/integer.html#packet-Protocol::LengthEncodedInteger).

> If the value is ≥ (2<sup>24</sup>) and < (2<sup>64</sup>) it is stored as `fe` + 8-byte integer.

`0xFE` is the same as the EOF packet signature, which causes the response to be incorrectly decoded as a (premature) EOF.
